### Localhost Variables
@localhost = http://localhost:8080

### GET all contacts
GET {{localhost}}/contacts

### GET contact by id
GET {{localhost}}/contacts/6966f1c47a777529f0b512a8

### POST create contact
POST {{localhost}}/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Yesid",
    "lastName": "Romero Ruiz",
    "email": "yesid@test.com",
    "favoriteColor": "Blue",
    "birthday": "1979-01-18"
}

### PUT update contact
PUT {{localhost}}/contacts/6966f1c47a777529f0b512a8 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Yesid Augusto",
    "lastName": "Romero Ruiz",
    "email": "yesid_updated@test.com",
    "favoriteColor": "Green",
    "birthday": "1979-01-18"
}

### DELETE contact
DELETE {{localhost}}/contacts/6966f1c47a777529f0b512a8 HTTP/1.1